PayPal: https://www.paypal.com/donate/?business=FQ3GNU47EP3MY&no_recurring=1&item_name=Tem+R%241%2C50+a%C3%AD+Paiz%C3%A3o?+%F0%9F%A5%BA&currency_code=BRL
Mercado Pago: link.mercadopago.com.br/warudo
PicPay: https://picpay.me/warudo750/0.5
NuBank (Pix): https://nubank.com.br/cobrar/ke2ok/68dc8235-2165-4be6-83fe-fe3cd4fd433e
